apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
spec:
  selector:
    matchLabels:
      app: k8-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: k8-deployment
    spec:
      containers:
        - name : cont-1
          image: venkat4540/final-project
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: final-project-svc
spec:
  type: NodePort
  selector:
    app: k8-deployment
  ports:
    - nodePort: 31068
      port: 8080
      targetPort: 8080
